from graphviz import Digraph

dot = Digraph(comment="The Round Table")
dot.node("d1", "fork()", shape="square")
dot.node("c1", "fork()", shape="square")
dot.node("c2", "fork()", shape="square")
dot.node("b1", "fork()", shape="square")
dot.node("b2", "fork()", shape="square")
dot.node("b3", "fork()", shape="square")
dot.node("b4", "fork()", shape="square")
dot.node("a1", "process", shape="square")
dot.node("a2", "process", shape="square")
dot.node("a3", "process", shape="square")
dot.node("a4", "process", shape="square")
dot.node("a5", "process", shape="square")
dot.node("a6", "process", shape="square")
dot.node("a7", "process", shape="square")
dot.node("a8", "process", shape="square")

dot.edge("d1", "c1")
dot.edge("d1", "c2")

dot.edge("c1", "b1")
dot.edge("c1", "b2")
dot.edge("c2", "b3")
dot.edge("c2", "b4")

dot.edge("b1", "a1")
dot.edge("b1", "a2")
dot.edge("b2", "a3")
dot.edge("b2", "a4")
dot.edge("b3", "a5")
dot.edge("b3", "a6")
dot.edge("b4", "a7")
dot.edge("b4", "a8")
dot.render("test-output/3.png", view=True)
